name: Run Capture Star Data

on:
  schedule:
    - cron: '*/30 * * * *'  # Executa a cada 30 minutos

jobs:
  run-script:
    runs-on: ubuntu-latest  # Pode ser alterado para outra imagem, se necessário
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'  # Altere para a versão do Python que você está usando

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 astropy

      - name: Run capture_star_data.py
        run: python capture_star_data.py
